[SLIDESHOW]

[MAIN]

globalpath = false
path = ItsLikeThis/
startimageclick = false ;play,next,false
autostart = true
autoscale = true
scaleup = false
keepaspect = true
imagesorting = nd
cacheimages = 3
minmargin = 60
maxwidth = false
maxheight = false
interval = 5
serverextension = php

[VISUAL]

startimage = false
displaykeyguide = true
backimage = backwall3.swf
backalign = M
bgcol = 360000
textcol = FFFFFF
tooltipforegroundcolor = textcol
tooltipbackgroundcolor = bgcol
framewidth = 15
innerframe = false
framecol = FFFFFF
frameshadow = true

[TRANSITION]

;motionmove,motionmask,blockmask,instant,tint,white,fade
;instant,tint,white
transition = motionmove,motionmask,blockmask,tint,white,fade
transitionresize = tint,white
frametransition = true

[AUDIO]

sfx = true
audio = true
audiopath = imagefolder
emptyaudio = mp3ss/
audiorepeat = 0
audioinit = true
audiostyle = linear
loopinterval = 30
audioextension = mp3
audioinfo = id3
audioplayercolor = textcol

[CONTROLS]

showmaincontrols = true
maincontrols = 1,1,1,0,1
enablerightclickcontrols = true
enablekeycontrols = true
imageclick = next
showpreloader = true
showaltpreloader = true
showtimer = true
preloadcolor = textcol
timercolor = textcol
controlsbackgroundcolor = textcol
controlsforegroundcolor = textcol
controlsbackalpha = 20
controlsbackoveralpha = 40
controlsbackpressalpha = 50
controlsdimensionx = 40
controlsdimensiony = 40
controlstooltip = true

[IMAGESELECT]

imageselecttooltip = true
imageselecttooltipdelay = 500
imageselecttooltiptext = true
imageselecttooltipthumbnail = true
timerselectreset = false

[TEXT]

displayposition = imagebottom
displayimageindex = false
displayname = true
displaydescription = false
formatmaxwidth = 250
formatminwidth = 150
formatmargin = 12
formatbackgroundcolor = textcol
formatbackgroundalpha = 0
defaultfont = Arial
defaultsize = 19
defaultcolor = textcol
defaultleading = 2
defaultalign = left
headingfont = DesertDogHmk
headingsize = 28
headingcolor = textcol
indexfont = Verdana
indexsize = 10
indexcolor = textcol
indexleading = 5
indexalign = left
namefont = Verdana
namesize = 10
namebold = false
namecolor = textcol
nameleading = 0
namealign = right
descriptionfont = Georgia
descriptionsize = 13
descriptioncolor = textcol
descriptionleading = 2
descriptionalign = left
selectfont = Georgia
selectsize = 13
selectbold = true
selectcolor = textcol
hideextension = false

[END]