<?php
/**
 * ConfigMagik - PHP 8 Updated Version
 * Original: r16 16.03.2005
 */

class Config {
    public ?string $PATH = null;
    public array $VARS = [];
    public bool $SYNCHRONIZE = false;
    public bool $PROCESS_SECTIONS = true;
    public bool $PROTECTED_MODE = true;
    public array $ERRORS = [];

    public function __construct(?string $path = null, bool $synchronize = false, bool $process_sections = true) {
        $this->PROCESS_SECTIONS = $process_sections;
        $this->SYNCHRONIZE = $synchronize;

        if ($path !== null) {
            $this->PATH = $path;
            if (!is_file($path)) {
                $fp_new = @fopen($path, 'w');
                if (!$fp_new) {
                    $err = "ConfigMagik() - Could not create new config-file('$path'), error.";
                    $this->ERRORS[] = $err;
                    die($err);
                } else {
                    fclose($fp_new);
                }
            } else {
                $loaded = $this->load($path);
                if (!$loaded) exit();
            }
        }
    }

    public function get(?string $key = null, ?string $section = null) {
        $this->PROCESS_SECTIONS = ($section !== null);

        if ($this->PROCESS_SECTIONS) {
            $value = $this->VARS[$section][$key] ?? null;
        } else {
            $value = $this->VARS[$key] ?? null;
        }

        return ($value === false) ? null : $value;
    }

    public function set(string $key, $value, ?string $section = null): bool {
        if ($this->PROCESS_SECTIONS && $section === null) {
            $err = "set() - Passed no section when in section-mode, nothing was set.";
            $this->ERRORS[] = $err;
            return false;
        }

        if ($this->PROCESS_SECTIONS) {
            $this->VARS[$section][$key] = $value;
        } else {
            $this->VARS[$key] = $value;
        }

        if ($this->SYNCHRONIZE) {
            $this->save();
        }
        return true;
    }

    public function removeKey(string $key, ?string $section = null): bool {
        if ($section !== null) {
            if (!isset($this->VARS[$section])) {
                $this->ERRORS[] = "removeKey() - Could not find section('$section').";
                return false;
            }
            if (!isset($this->VARS[$section][$key])) {
                $this->ERRORS[] = "removeKey() - Could not find key('$key') in section.";
                return false;
            }
            unset($this->VARS[$section][$key]);
        } else {
            if (!isset($this->VARS[$key])) {
                $this->ERRORS[] = "removeKey() - Could not find key('$key').";
                return false;
            }
            unset($this->VARS[$key]);
        }

        if ($this->SYNCHRONIZE) $this->save();
        return true;
    }

    public function removeSection(string $section): bool {
        if (!isset($this->VARS[$section])) {
            $this->ERRORS[] = "removeSection() - Section('$section') not found.";
            return false;
        }
        unset($this->VARS[$section]);
        if ($this->SYNCHRONIZE) $this->save();
        return true;
    }

    public function load(?string $path = null): bool {
        $path = $path ?? $this->PATH;

        if ($path === null || !is_file($path)) {
            $err = "load() - Path is invalid, nothing loaded.";
            $this->ERRORS[] = $err;
            return false;
        }

        $this->VARS = parse_ini_file($path, $this->PROCESS_SECTIONS);
        return true;
    }

    public function save(?string $path = null): bool {
        $path = $path ?? $this->PATH;
        $content = "";

        if ($this->PROTECTED_MODE) {
            $content .= "<?PHP\n; /*\n; -- BEGIN PROTECTED_MODE\n";
        }

        $content .= "; Generated by ConfigMagik PHP 8\n";
        $content .= "; Last modified: " . date('d M Y H:i:s') . "\n";

        if ($this->PROCESS_SECTIONS) {
            foreach ($this->VARS as $section => $items) {
                if (is_array($items)) {
                    $content .= "[" . $section . "]\n";
                    foreach ($items as $k => $v) {
                        $content .= "$k = \"$v\"\n";
                    }
                }
            }
        } else {
            foreach ($this->VARS as $k => $v) {
                if (!is_array($v)) {
                    $content .= "$k = \"$v\"\n";
                }
            }
        }

        if ($this->PROTECTED_MODE) {
            $content .= "\n; -- END PROTECTED_MODE\n; */\n?>\n";
        }

        if (!$handle = @fopen($path, 'w')) {
            $this->ERRORS[] = "save() - Could not open file for writing.";
            return false;
        }
        
        fwrite($handle, $content);
        fclose($handle);
        return true;
    }

    public function toString(string $output_type = 'TEXT', ?string $sect = null, bool $urle = false): string {
        $out = '';
        $output_type = strtoupper($output_type);
        if ($sect) $sect = strtoupper($sect);

        if ($output_type === 'TEXT') {
            $sections = $this->listSections();
            if ($sect && in_array($sect, $sections)) $sections = [$sect];
            
            foreach ($sections as $section) {
                $keys = $this->listKeys($section);
                foreach ($keys as $key) {
                    $val = $this->get($key, $section);
                    if ($urle) $val = urlencode((string)$val);
                    $out .= $key . "=" . $val . "&";
                }
            }
            return $out;
        }

        if ($output_type === 'XML') {
            $out = "<index>\n";
            $sections = $this->listSections();
            if ($sect && in_array($sect, $sections)) $sections = [$sect];
            
            foreach ($sections as $section) {
                $out .= "\t<section name=\"$section\">\n";
                $keys = $this->listKeys($section);
                foreach ($keys as $key) {
                    $val = $this->get($key, $section);
                    $out .= "\t\t<item name=\"$key\" value=\"$val\"/>\n";
                }
                $out .= "\t</section>\n";
            }
            $out .= "</index>";
            return $out;
        }

        if ($output_type === 'HTML') {
            $out = "<table style='border:1px solid grey; font-family: verdana; font-size: 10px;' width='60%'>\n";
            $sections = $this->listSections();
            if ($sect && in_array($sect, $sections)) $sections = [$sect];

            $num_keys = 0;
            foreach ($sections as $section) {
                $out .= "<tr><td colspan='2'><b>$section</b></td></tr>\n";
                $keys = $this->listKeys($section);
                foreach ($keys as $key) {
                    $val = $this->get($key, $section);
                    $out .= "<tr><td>$key</td><td>$val</td></tr>\n";
                    $num_keys++;
                }
            }
            $out .= "<tr><td colspan='2' align='right'>Total: $num_keys keys</td></tr>\n</table>";
            return $out;
        }

        return "Unknown Output Type";
    }

    public function listKeys(?string $section = null): array {
        if ($section !== null) {
            if (!isset($this->VARS[$section]) || !is_array($this->VARS[$section])) {
                return [];
            }
            return array_keys($this->VARS[$section]);
        }
        return array_keys($this->VARS);
    }

    public function listSections(): array {
        $list = [];
        foreach ($this->VARS as $key => $value) {
            if (is_array($value)) {
                $list[] = strtoupper((string)$key);
            }
        }
        return $list;
    }
}