[SLIDESHOW]

[MAIN]

globalpath = false
path = pageshow/
startimageclick = false ;play,next,false
autostart = true
autoscale = true
scaleup = false
keepaspect = true
imagesorting = na
cacheimages = 3
minmargin = 0
maxwidth = false
maxheight = false
interval = 3
serverextension = php

[VISUAL]

startimage = false
displaykeyguide = true
backimage = false
backalign = M
bgcol = FFFFFF
textcol = FFFFFF
tooltipforegroundcolor = FFFFFF
tooltipbackgroundcolor = 000000
framewidth = 2
innerframe = true
framecol = CCCCCC
frameshadow = false

[TRANSITION]

;motionmove,motionmask,blockmask,instant,tint,white,fade
;instant,tint,white
transition = motionmove,motionmask,blockmask,white,fade
transitionresize = tint,white
frametransition = true

[AUDIO]

sfx = false
audio = false
audiopath = imagefolder
emptyaudio = mp3ss/
audiorepeat = 0
audioinit = false
audiostyle = linear
loopinterval = 30
audioextension = mp3
audioinfo = id3
audioplayercolor = textcol

[CONTROLS]

showmaincontrols = false
maincontrols = 1,1,1,0,1
enablerightclickcontrols = true
enablekeycontrols = true
imageclick = next
showpreloader = false
showaltpreloader = false
showtimer = false
preloadcolor = textcol
timercolor = FFFFFF
controlsbackgroundcolor = 000000
controlsforegroundcolor = FFFFFF
controlsbackalpha = 40
controlsbackoveralpha = 60
controlsbackpressalpha = 40
controlsdimensionx = 30
controlsdimensiony = 30
controlstooltip = true

[IMAGESELECT]

imageselecttooltip = false
imageselecttooltipdelay = 500
imageselecttooltiptext = false
imageselecttooltipthumbnail = true
timerselectreset = 3000

[TEXT]

displayposition = imagetop
displayimageindex = false
displayname = false
displaydescription = true
formatmaxwidth = 250
formatminwidth = 150
formatmargin = 10
formatbackgroundcolor = 000000
formatbackgroundalpha = 50
defaultfont = Arial
defaultsize = 19
defaultcolor = textcol
defaultleading = 2
defaultalign = left
headingfont = DesertDogHmk
headingsize = 28
headingcolor = textcol
indexfont = Verdana
indexsize = 10
indexcolor = textcol
indexleading = 5
indexalign = left
namefont = Georgia
namesize = 17
namebold = true
namecolor = textcol
nameleading = 8
namealign = left
descriptionfont = Georgia
descriptionsize = 13
descriptioncolor = textcol
descriptionleading = 2
descriptionalign = left
selectfont = Georgia
selectsize = 11
selectbold = true
selectcolor = textcol
hideextension = true

[END]