[SLIDESHOW]

[MAIN]

globalpath = false
path = organica waves/
startimageclick = false ;play,next,false
autostart = true
autoscale = true
scaleup = false
keepaspect = true
imagesorting = na
cacheimages = 3
minmargin = 50
maxwidth = false
maxheight = false
interval = 1
serverextension = php

[VISUAL]

startimage = false
displaykeyguide = true
backimage = backwall2.swf
backalign = M
bgcol = C6D1DB
textcol = 003366
tooltipforegroundcolor = textcol
tooltipbackgroundcolor = bgcol
framewidth = 20
innerframe = true
framecol = 000000
frameshadow = true

[TRANSITION]

;motionmove,motionmask,blockmask,instant,tint,white,fade
;instant,tint,white
transition = motionmask,motionmove
transitionresize = white
frametransition = true

[AUDIO]

sfx = true
audio = true
audiopath = imagefolder
emptyaudio = mp3ss/
audiorepeat = 0
audioinit = false
audiostyle = linear
loopinterval = 30
audioextension = mp3
audioinfo = id3
audioplayercolor = textcol

[CONTROLS]

showmaincontrols = true
maincontrols = 1,1,1,0,1
enablerightclickcontrols = true
enablekeycontrols = true
imageclick = next
showpreloader = true
showaltpreloader = true
showtimer = true
preloadcolor = textcol
timercolor = textcol
controlsbackgroundcolor = textcol
controlsforegroundcolor = textcol
controlsbackalpha = 40
controlsbackoveralpha = 60
controlsbackpressalpha = 70
controlsdimensionx = 30
controlsdimensiony = 30
controlstooltip = true

[IMAGESELECT]

imageselecttooltip = true
imageselecttooltipdelay = 500
imageselecttooltiptext = false
imageselecttooltipthumbnail = true
timerselectreset = false

[TEXT]

displayposition = above
displayimageindex = true
displayname = false
displaydescription = false
formatmaxwidth = 250
formatminwidth = 150
formatmargin = 10
formatbackgroundcolor = textcol
formatbackgroundalpha = 0
defaultfont = Arial
defaultsize = 19
defaultcolor = textcol
defaultleading = 2
defaultalign = left
headingfont = DesertDogHmk
headingsize = 28
headingcolor = textcol
indexfont = Georgia
indexsize = 13
indexcolor = textcol
indexbold = true
indexleading = 0
indexalign = center
namefont = Georgia
namesize = 17
namebold = true
namecolor = textcol
nameleading = 8
namealign = left
descriptionfont = Georgia
descriptionsize = 13
descriptioncolor = textcol
descriptionleading = 2
descriptionalign = left
selectfont = Georgia
selectsize = 10
selectbold = true
selectcolor = textcol
hideextension = true

[END]