globalStyleFormat.textFont = "standard 07_53";
globalStyleFormat.textSize = 8;
globalStyleFormat.textColor = 0x333333;
globalStyleFormat.embedFonts = true;
globalStyleFormat.applyChanges();
_global.standardformat = new TextFormat();
_global.standardformat.font = "standard 07_53";
_global.standardformat.size = "8";
_global.standardformat.color = 0x333333;
_global.standardformat.embedFonts = true;
_global.standardformat.leading = 1;
_global.standardformat63 = new TextFormat();
_global.standardformat63.copyFormat(standardformat);
_global.standardformat63.font = "standard 07_63";
_global.standardlistformat = new TextFormat();
_global.standardlistformat.copyFormat(standardformat);
_global.standardlistformat.leading = 3;
_global.verdanaformat = new TextFormat();
_global.verdanaformat.font = "Verdana";
_global.verdanaformat.size = "10";
_global.verdanaformat.color = 0x333333;
_global.verdanaformat.leading = 1;
_global.verdanaformat.html = true;
_global.verdanaformat.multiline = true;
_global.verdanaformat.wordWrap = true;
_global.attformat = new TextFormat();
_global.attformat.size = "8";
_global.attformat.color = 0x333333;
_global.attformat.leading = 2;