[SLIDESHOW]

[MAIN]

globalpath = false
path = Trees and Bushes/
startimageclick = next ;play,next,false
autostart = true
autoscale = true
scaleup = false
keepaspect = true
imagesorting = na
cacheimages = 3
minmargin = 50
maxwidth = false
maxheight = false
interval = 4
serverextension = php

[VISUAL]

startimage = false
displaykeyguide = false
backimage = false
backalign = M
bgcol = FFFFFF
textcol = 999999
tooltipforegroundcolor = textcol
tooltipbackgroundcolor = E7E7E7
framewidth = 1
innerframe = false
framecol = FFFFFF
frameshadow = false

[TRANSITION]

;motionmove,motionmask,blockmask,instant,tint,white,fade
;instant,tint,white
transition = fade
transitionresize = tint
frametransition = true

[AUDIO]

sfx = true
audio = false
audiopath = imagefolder
emptyaudio = mp3ss/
audiorepeat = 0
audioinit = false
audiostyle = linear
loopinterval = 30
audioextension = mp3
audioinfo = id3
audioplayercolor = textcol

[CONTROLS]

showmaincontrols = true
maincontrols = 1,1,1,0,1
enablerightclickcontrols = true
enablekeycontrols = true
imageclick = next
showpreloader = true
showaltpreloader = true
showtimer = true
preloadcolor = textcol
timercolor = textcol
controlsbackgroundcolor = textcol
controlsforegroundcolor = textcol
controlsbackalpha = 20
controlsbackoveralpha = 40
controlsbackpressalpha = 50
controlsdimensionx = 35
controlsdimensiony = 35
controlstooltip = true

[IMAGESELECT]

imageselecttooltip = true
imageselecttooltipdelay = 500
imageselecttooltiptext = true
imageselecttooltipthumbnail = true
timerselectreset = false

[TEXT]

displayposition = above
displayimageindex = false
displayname = true
displaydescription = false
formatmaxwidth = 250
formatminwidth = 150
formatmargin = 5
formatbackgroundcolor = textcol
formatbackgroundalpha = 0
defaultfont = Arial
defaultsize = 19
defaultcolor = textcol
defaultleading = 2
defaultalign = left
headingfont = DesertDogHmk
headingsize = 28
headingcolor = textcol
indexfont = Georgia
indexsize = 11
indexcolor = textcol
indexleading = 5
indexalign = left
namefont = Verdana
namesize = 10
namebold = false
namecolor = textcol
nameleading = 8
namealign = center
descriptionfont = Georgia
descriptionsize = 13
descriptioncolor = 336600
descriptionleading = 2
descriptionalign = left
selectfont = Georgia
selectsize = 11
selectbold = true
selectcolor = textcol
hideextension = true

[END]